siteTitle = 'Đồ Nhà mới Phú Quốc'
siteDescr = 'Tân trang homestay'
siteDescription = "Tôi Phạm Xuân Tiếp, tổng hợp những món đồ mà mình cần trong cuộc sống và công việc để khi đủ tiền thì rinh món đồ đó về nhà"
siteUrl = "https://fnote.co"
siteBandcampUrl = 'https://fnote.co'
siteMenuOne = 'Nên mua'
siteMenuTwo = 'Đã có'
siteMenuThree = 'Quan tâm'
siteAddress = '165 Nguyễn Trung Trực, Thị trấn Dương Đông, Thành phố Phú Quốc'
siteAddress2 = 'Tỉnh Kiên Giang, Việt Nam. Postal code 920000'
sitePhone = '093-887-8827'
sitePhoneLink = 'tel:+84-93-887-8827'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/OdayakaPhuQuoc'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/OdayakaPhuQuoc'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
